# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'repsy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for repsy
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'


end
