# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'repsy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for repsy

  pod 'Firebase/Core'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Phone'


end
